title: Fluent-plugin-azurefunctions
description: Azure Functions (HTTP Trigger) output plugin for Fluentd
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
